<a href="https://colab.research.google.com/github/ARMargolis/Labs/blob/master/sailor_health.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np, pandas as pd

#get the submission file from GitHub
url='https://raw.githubusercontent.com/TRACK2-DATA-SCIENCE-2021/Track2_Challenges_Data/main/Challenge3/submissions/Challenge3_Day1Submission_sample.csv'
submission=pd.read_csv(url)
submission.tail()

    ID  Health  Rate of health decline  ...  Supplemental oxygen  Chloroquine  Total
0    1     100                      -1  ...                    0            0     99
1    2      75                      -1  ...                    0            0     74
2    3      65                      -7  ...                    0            0     58
3    4      55                     -25  ...                    0            0     30
4    5      33                     -30  ...                    0            0      3
5    6      89                     -50  ...                    0            0     39
6    7      90                     -60  ...                    0            0     30
7    8      45                     -65  ...                    0            0    -20
8    9     100                     -79  ...                    0            0     21
9   10      95                     -88  ...                    0            0      7
10  11      60                     -62  ...                    0            0     -2
11  12      72                     -18  ...                    0            0     54
12  13      55                     -68  ...                    0            0    -13
13  14      28                     -67  ...                    0            0    -39
14  15      39                     -89  ...                    0            0    -50
15  16      91                     -13  ...                    0            0     78
16  17      95                      -7  ...                    0            0     88
17  18      99                      -1  ...                    0            0     98
18  19      88                     -25  ...                    0            0     63
19  20      20                     -80  ...                    0            0    -60

[20 rows x 12 columns]

In [14]:
import numpy as np

#Vector for quick addition of treatment
treatment_vec=np.array([0,1,1,5,30, 30,25,15,15,20,10])

#Sort sailors based on their predicted health at the end of day 2 with no treatment
day2health=sample['Health']+2*sample['Rate of health decline']
sickest_sailors=day2health.values.argsort(kind='mergesort')

#Put the thirty sickest (or all) sailors in beds
if submission.shape[0]<30:
  submission['Bed']=1
else:
  submission.loc[sickest_sailors[:30], 'Bed']=1

#Give the ten sickest (or all) sailors  ventilators 
if submission.shape[0]<10:
  submission['Ventilator']=1
else:
  submission.loc[sickest_sailors[:10], 'Ventilator']=1
  #Give the next ten sickest (or all) sailors sumplemental oxygen
  if submission.shape[0]<20:
    submission.loc[10:submission.shape[0], 'Supplemental oxygen']=1
  else:
    submission.loc[sickest_sailors[10:20], 'Supplemental oxygen']=1

#Recalculate total
submission['Total']=np.matmul(submission.values[:,:-1], treatment_vec)
submission

    ID  Health  Rate of health decline  ...  Supplemental oxygen  Chloroquine  Total
0    1     100                      -1  ...                    1            0    124
1    2      75                      -1  ...                    1            0     99
2    3      65                      -7  ...                    1            0     83
3    4      55                     -25  ...                    1            0     55
4    5      33                     -30  ...                    0            0     38
5    6      89                     -50  ...                    1            0     64
6    7      90                     -60  ...                    0            0     65
7    8      45                     -65  ...                    0            0     15
8    9     100                     -79  ...                    0            0     56
9   10      95                     -88  ...                    0            0     42
10  11      60                     -62  ...                    0            0     33
11  12      72                     -18  ...                    1            0     79
12  13      55                     -68  ...                    0            0     22
13  14      28                     -67  ...                    0            0     -4
14  15      39                     -89  ...                    0            0    -15
15  16      91                     -13  ...                    1            0    103
16  17      95                      -7  ...                    1            0    113
17  18      99                      -1  ...                    1            0    123
18  19      88                     -25  ...                    1            0     88
19  20      20                     -80  ...                    0            0    -25

[20 rows x 12 columns]